version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app:latest
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      PHP_IDE_CONFIG: serverName=laravel-app
      APP_DEBUG: "true"
    volumes:
      - ./laravel-app:/var/www/html
      - ./laravel-app/storage:/var/www/html/storage
      - /var/www/html/vendor
      - /var/www/html/node_modules
      - app-cache:/var/www/.npm
    networks:
      - laravel-network
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: nginx-laravel
    restart: unless-stopped
    ports:
      - "8010:80"
    volumes:
      - ./laravel-app:/var/www/html
      - ./nginx/laravel.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-network

  db:
    image: mysql:8.0
    container_name: mysql-laravel
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: secret_laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret_laravel
    ports:
      - "3308:3306"
    volumes:
      - dbdata-laravel:/var/lib/mysql
    networks:
      - laravel-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  dbdata-laravel:
    driver: local
  app-cache:
    driver: local

networks:
  laravel-network:
    driver: bridge
