version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./laravel-app:/var/www/html
      - ./laravel-app/storage:/var/www/html/storage
      - ./laravel-app/vendor:/var/www/html/vendor
      - ./laravel-app/node_modules:/var/www/html/node_modules
    networks:
      - laravel-network

  webserver:
    image: nginx:alpine
    container_name: nginx-laravel
    restart: unless-stopped
    ports:
      - "8010:80"
    volumes:
      - ./laravel-app:/var/www/html
      - ./nginx/laravel.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-network

  db:
    image: mysql:8.0
    container_name: mysql-laravel
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: secret_laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret_laravel
    ports:
      - "3308:3306"
    volumes:
      - dbdata-laravel:/var/lib/mysql
    networks:
      - laravel-network

volumes:
  dbdata-laravel:

networks:
  laravel-network: